version: "3"
services:

  jenkins:
    build: ./
#    privileged: true # "the container can then do almost everything that the host can do"
    user: root
    ports:
      - "8080:8080"
#      - "50000:50000"
    container_name: jenkins
    volumes: 
      - ./jenkins:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker 
